apiVersion: v1
kind: Namespace
metadata:
  name: wiz-exercise
  labels:
    app: tasky
    project: wiz-exercise
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
